//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PayID { get; set; }
        public double Amount { get; set; }
        public string PayType { get; set; }
        public int CustomerID { get; set; }
        public int CartID { get; set; }
        public System.DateTime PayDate { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Userss Userss { get; set; }
    }
}
