//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string PictureName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int IsActive { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
    }
}
